// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package team

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-heroku/sdk/go/heroku/internal"
)

func GetMembers(ctx *pulumi.Context, args *GetMembersArgs, opts ...pulumi.InvokeOption) (*GetMembersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetMembersResult
	err := ctx.Invoke("heroku:team/getMembers:getMembers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getMembers.
type GetMembersArgs struct {
	Roles []string `pulumi:"roles"`
	Team  string   `pulumi:"team"`
}

// A collection of values returned by getMembers.
type GetMembersResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id      string             `pulumi:"id"`
	Members []GetMembersMember `pulumi:"members"`
	Roles   []string           `pulumi:"roles"`
	Team    string             `pulumi:"team"`
}

func GetMembersOutput(ctx *pulumi.Context, args GetMembersOutputArgs, opts ...pulumi.InvokeOption) GetMembersResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetMembersResult, error) {
			args := v.(GetMembersArgs)
			r, err := GetMembers(ctx, &args, opts...)
			var s GetMembersResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetMembersResultOutput)
}

// A collection of arguments for invoking getMembers.
type GetMembersOutputArgs struct {
	Roles pulumi.StringArrayInput `pulumi:"roles"`
	Team  pulumi.StringInput      `pulumi:"team"`
}

func (GetMembersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMembersArgs)(nil)).Elem()
}

// A collection of values returned by getMembers.
type GetMembersResultOutput struct{ *pulumi.OutputState }

func (GetMembersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetMembersResult)(nil)).Elem()
}

func (o GetMembersResultOutput) ToGetMembersResultOutput() GetMembersResultOutput {
	return o
}

func (o GetMembersResultOutput) ToGetMembersResultOutputWithContext(ctx context.Context) GetMembersResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetMembersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetMembersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetMembersResultOutput) Members() GetMembersMemberArrayOutput {
	return o.ApplyT(func(v GetMembersResult) []GetMembersMember { return v.Members }).(GetMembersMemberArrayOutput)
}

func (o GetMembersResultOutput) Roles() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetMembersResult) []string { return v.Roles }).(pulumi.StringArrayOutput)
}

func (o GetMembersResultOutput) Team() pulumi.StringOutput {
	return o.ApplyT(func(v GetMembersResult) string { return v.Team }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetMembersResultOutput{})
}
