// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Use this data source to get information about members for a Heroku Team.
 *
 * ## Example Usage
 */
export function getMembers(args: GetMembersArgs, opts?: pulumi.InvokeOptions): Promise<GetMembersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("heroku:team/getMembers:getMembers", {
        "roles": args.roles,
        "team": args.team,
    }, opts);
}

/**
 * A collection of arguments for invoking getMembers.
 */
export interface GetMembersArgs {
    /**
     * List of roles. Acceptable values are `admin`, `member`, `viewer`, `collaborator`, `owner`.
     * At least one role must be specified.
     */
    roles: string[];
    /**
     * The team name.
     */
    team: string;
}

/**
 * A collection of values returned by getMembers.
 */
export interface GetMembersResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * All members of the team that have a specified role defined in the `roles` attribute above.
     */
    readonly members: outputs.team.GetMembersMember[];
    readonly roles: string[];
    readonly team: string;
}
/**
 * Use this data source to get information about members for a Heroku Team.
 *
 * ## Example Usage
 */
export function getMembersOutput(args: GetMembersOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetMembersResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("heroku:team/getMembers:getMembers", {
        "roles": args.roles,
        "team": args.team,
    }, opts);
}

/**
 * A collection of arguments for invoking getMembers.
 */
export interface GetMembersOutputArgs {
    /**
     * List of roles. Acceptable values are `admin`, `member`, `viewer`, `collaborator`, `owner`.
     * At least one role must be specified.
     */
    roles: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The team name.
     */
    team: pulumi.Input<string>;
}
