// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * A [Heroku Collaborator](https://devcenter.heroku.com/articles/platform-api-reference#collaborator)
 * receives access to a specific app that is not owned by a team.
 *
 * > **IMPORTANT!:**
 * This resource only works for apps that are not part of a team.
 *
 * ## Example Usage
 *
 * ## Import
 *
 * Collaborators can be imported using the combination of the application name, a colon, and the collaborator's email address
 *
 * For example:
 *
 * ```sh
 * $ pulumi import heroku:collaborator/collaborator:Collaborator foobar-collaborator foobar_app:collaborator@foobar.com
 * ```
 */
export class Collaborator extends pulumi.CustomResource {
    /**
     * Get an existing Collaborator resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CollaboratorState, opts?: pulumi.CustomResourceOptions): Collaborator {
        return new Collaborator(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'heroku:collaborator/collaborator:Collaborator';

    /**
     * Returns true if the given object is an instance of Collaborator.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Collaborator {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Collaborator.__pulumiType;
    }

    /**
     * Heroku app ID (do not use app name)
     */
    public readonly appId!: pulumi.Output<string>;
    /**
     * Email address of the collaborator
     */
    public readonly email!: pulumi.Output<string>;

    /**
     * Create a Collaborator resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CollaboratorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CollaboratorArgs | CollaboratorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CollaboratorState | undefined;
            resourceInputs["appId"] = state ? state.appId : undefined;
            resourceInputs["email"] = state ? state.email : undefined;
        } else {
            const args = argsOrState as CollaboratorArgs | undefined;
            if ((!args || args.appId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if ((!args || args.email === undefined) && !opts.urn) {
                throw new Error("Missing required property 'email'");
            }
            resourceInputs["appId"] = args ? args.appId : undefined;
            resourceInputs["email"] = args ? args.email : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Collaborator.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Collaborator resources.
 */
export interface CollaboratorState {
    /**
     * Heroku app ID (do not use app name)
     */
    appId?: pulumi.Input<string>;
    /**
     * Email address of the collaborator
     */
    email?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Collaborator resource.
 */
export interface CollaboratorArgs {
    /**
     * Heroku app ID (do not use app name)
     */
    appId: pulumi.Input<string>;
    /**
     * Email address of the collaborator
     */
    email: pulumi.Input<string>;
}
