// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Heroku.App
{
    public static class GetApp
    {
        public static Task<GetAppResult> InvokeAsync(GetAppArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAppResult>("heroku:app/getApp:getApp", args ?? new GetAppArgs(), options.WithDefaults());

        public static Output<GetAppResult> Invoke(GetAppInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAppResult>("heroku:app/getApp:getApp", args ?? new GetAppInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetAppArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetAppArgs()
        {
        }
        public static new GetAppArgs Empty => new GetAppArgs();
    }

    public sealed class GetAppInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetAppInvokeArgs()
        {
        }
        public static new GetAppInvokeArgs Empty => new GetAppInvokeArgs();
    }


    [OutputType]
    public sealed class GetAppResult
    {
        public readonly bool Acm;
        public readonly ImmutableArray<string> Buildpacks;
        public readonly ImmutableDictionary<string, object> ConfigVars;
        public readonly string GitUrl;
        public readonly string HerokuHostname;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly bool InternalRouting;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.GetAppOrganizationResult> Organizations;
        public readonly string Region;
        public readonly string Space;
        public readonly string Stack;
        public readonly string Uuid;
        public readonly string WebUrl;

        [OutputConstructor]
        private GetAppResult(
            bool acm,

            ImmutableArray<string> buildpacks,

            ImmutableDictionary<string, object> configVars,

            string gitUrl,

            string herokuHostname,

            string id,

            bool internalRouting,

            string name,

            ImmutableArray<Outputs.GetAppOrganizationResult> organizations,

            string region,

            string space,

            string stack,

            string uuid,

            string webUrl)
        {
            Acm = acm;
            Buildpacks = buildpacks;
            ConfigVars = configVars;
            GitUrl = gitUrl;
            HerokuHostname = herokuHostname;
            Id = id;
            InternalRouting = internalRouting;
            Name = name;
            Organizations = organizations;
            Region = region;
            Space = space;
            Stack = stack;
            Uuid = uuid;
            WebUrl = webUrl;
        }
    }
}
