# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'GetMembersMemberResult',
]

@pulumi.output_type
class GetMembersMemberResult(dict):
    def __init__(__self__, *,
                 email: str,
                 federated: bool,
                 role: str,
                 team_member_id: str,
                 two_factor_authentication: bool,
                 user_id: str):
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "federated", federated)
        pulumi.set(__self__, "role", role)
        pulumi.set(__self__, "team_member_id", team_member_id)
        pulumi.set(__self__, "two_factor_authentication", two_factor_authentication)
        pulumi.set(__self__, "user_id", user_id)

    @property
    @pulumi.getter
    def email(self) -> str:
        return pulumi.get(self, "email")

    @property
    @pulumi.getter
    def federated(self) -> bool:
        return pulumi.get(self, "federated")

    @property
    @pulumi.getter
    def role(self) -> str:
        return pulumi.get(self, "role")

    @property
    @pulumi.getter(name="teamMemberId")
    def team_member_id(self) -> str:
        return pulumi.get(self, "team_member_id")

    @property
    @pulumi.getter(name="twoFactorAuthentication")
    def two_factor_authentication(self) -> bool:
        return pulumi.get(self, "two_factor_authentication")

    @property
    @pulumi.getter(name="userId")
    def user_id(self) -> str:
        return pulumi.get(self, "user_id")


