# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'SlugBlob',
]

@pulumi.output_type
class SlugBlob(dict):
    def __init__(__self__, *,
                 method: Optional[str] = None,
                 url: Optional[str] = None):
        if method is not None:
            pulumi.set(__self__, "method", method)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @property
    @pulumi.getter
    def method(self) -> Optional[str]:
        return pulumi.get(self, "method")

    @property
    @pulumi.getter
    def url(self) -> Optional[str]:
        return pulumi.get(self, "url")


