// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package review

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-heroku/sdk/go/heroku/internal"
)

var _ = internal.GetEnvOrDefault

type AppConfigDeployTarget struct {
	// Unique identifier of deploy target.
	Id string `pulumi:"id"`
	// Type of deploy target. Must be either `space` or `region`.
	Type string `pulumi:"type"`
}

// AppConfigDeployTargetInput is an input type that accepts AppConfigDeployTargetArgs and AppConfigDeployTargetOutput values.
// You can construct a concrete instance of `AppConfigDeployTargetInput` via:
//
//	AppConfigDeployTargetArgs{...}
type AppConfigDeployTargetInput interface {
	pulumi.Input

	ToAppConfigDeployTargetOutput() AppConfigDeployTargetOutput
	ToAppConfigDeployTargetOutputWithContext(context.Context) AppConfigDeployTargetOutput
}

type AppConfigDeployTargetArgs struct {
	// Unique identifier of deploy target.
	Id pulumi.StringInput `pulumi:"id"`
	// Type of deploy target. Must be either `space` or `region`.
	Type pulumi.StringInput `pulumi:"type"`
}

func (AppConfigDeployTargetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*AppConfigDeployTarget)(nil)).Elem()
}

func (i AppConfigDeployTargetArgs) ToAppConfigDeployTargetOutput() AppConfigDeployTargetOutput {
	return i.ToAppConfigDeployTargetOutputWithContext(context.Background())
}

func (i AppConfigDeployTargetArgs) ToAppConfigDeployTargetOutputWithContext(ctx context.Context) AppConfigDeployTargetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppConfigDeployTargetOutput)
}

func (i AppConfigDeployTargetArgs) ToAppConfigDeployTargetPtrOutput() AppConfigDeployTargetPtrOutput {
	return i.ToAppConfigDeployTargetPtrOutputWithContext(context.Background())
}

func (i AppConfigDeployTargetArgs) ToAppConfigDeployTargetPtrOutputWithContext(ctx context.Context) AppConfigDeployTargetPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppConfigDeployTargetOutput).ToAppConfigDeployTargetPtrOutputWithContext(ctx)
}

// AppConfigDeployTargetPtrInput is an input type that accepts AppConfigDeployTargetArgs, AppConfigDeployTargetPtr and AppConfigDeployTargetPtrOutput values.
// You can construct a concrete instance of `AppConfigDeployTargetPtrInput` via:
//
//	        AppConfigDeployTargetArgs{...}
//
//	or:
//
//	        nil
type AppConfigDeployTargetPtrInput interface {
	pulumi.Input

	ToAppConfigDeployTargetPtrOutput() AppConfigDeployTargetPtrOutput
	ToAppConfigDeployTargetPtrOutputWithContext(context.Context) AppConfigDeployTargetPtrOutput
}

type appConfigDeployTargetPtrType AppConfigDeployTargetArgs

func AppConfigDeployTargetPtr(v *AppConfigDeployTargetArgs) AppConfigDeployTargetPtrInput {
	return (*appConfigDeployTargetPtrType)(v)
}

func (*appConfigDeployTargetPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**AppConfigDeployTarget)(nil)).Elem()
}

func (i *appConfigDeployTargetPtrType) ToAppConfigDeployTargetPtrOutput() AppConfigDeployTargetPtrOutput {
	return i.ToAppConfigDeployTargetPtrOutputWithContext(context.Background())
}

func (i *appConfigDeployTargetPtrType) ToAppConfigDeployTargetPtrOutputWithContext(ctx context.Context) AppConfigDeployTargetPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(AppConfigDeployTargetPtrOutput)
}

type AppConfigDeployTargetOutput struct{ *pulumi.OutputState }

func (AppConfigDeployTargetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*AppConfigDeployTarget)(nil)).Elem()
}

func (o AppConfigDeployTargetOutput) ToAppConfigDeployTargetOutput() AppConfigDeployTargetOutput {
	return o
}

func (o AppConfigDeployTargetOutput) ToAppConfigDeployTargetOutputWithContext(ctx context.Context) AppConfigDeployTargetOutput {
	return o
}

func (o AppConfigDeployTargetOutput) ToAppConfigDeployTargetPtrOutput() AppConfigDeployTargetPtrOutput {
	return o.ToAppConfigDeployTargetPtrOutputWithContext(context.Background())
}

func (o AppConfigDeployTargetOutput) ToAppConfigDeployTargetPtrOutputWithContext(ctx context.Context) AppConfigDeployTargetPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v AppConfigDeployTarget) *AppConfigDeployTarget {
		return &v
	}).(AppConfigDeployTargetPtrOutput)
}

// Unique identifier of deploy target.
func (o AppConfigDeployTargetOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v AppConfigDeployTarget) string { return v.Id }).(pulumi.StringOutput)
}

// Type of deploy target. Must be either `space` or `region`.
func (o AppConfigDeployTargetOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v AppConfigDeployTarget) string { return v.Type }).(pulumi.StringOutput)
}

type AppConfigDeployTargetPtrOutput struct{ *pulumi.OutputState }

func (AppConfigDeployTargetPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**AppConfigDeployTarget)(nil)).Elem()
}

func (o AppConfigDeployTargetPtrOutput) ToAppConfigDeployTargetPtrOutput() AppConfigDeployTargetPtrOutput {
	return o
}

func (o AppConfigDeployTargetPtrOutput) ToAppConfigDeployTargetPtrOutputWithContext(ctx context.Context) AppConfigDeployTargetPtrOutput {
	return o
}

func (o AppConfigDeployTargetPtrOutput) Elem() AppConfigDeployTargetOutput {
	return o.ApplyT(func(v *AppConfigDeployTarget) AppConfigDeployTarget {
		if v != nil {
			return *v
		}
		var ret AppConfigDeployTarget
		return ret
	}).(AppConfigDeployTargetOutput)
}

// Unique identifier of deploy target.
func (o AppConfigDeployTargetPtrOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AppConfigDeployTarget) *string {
		if v == nil {
			return nil
		}
		return &v.Id
	}).(pulumi.StringPtrOutput)
}

// Type of deploy target. Must be either `space` or `region`.
func (o AppConfigDeployTargetPtrOutput) Type() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *AppConfigDeployTarget) *string {
		if v == nil {
			return nil
		}
		return &v.Type
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*AppConfigDeployTargetInput)(nil)).Elem(), AppConfigDeployTargetArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*AppConfigDeployTargetPtrInput)(nil)).Elem(), AppConfigDeployTargetArgs{})
	pulumi.RegisterOutputType(AppConfigDeployTargetOutput{})
	pulumi.RegisterOutputType(AppConfigDeployTargetPtrOutput{})
}
