// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Heroku.Drain
{
    /// <summary>
    /// Provides a Heroku Drain resource. This can be used to
    /// create and manage Log Drains on Heroku.
    /// 
    /// ## Example Usage
    /// 
    /// ## Importing
    /// 
    /// When importing a Heroku drain resource, the ID must be built using the app name colon the unique ID from the Heroku API.
    /// For an app named `production-api` with a drain ID of `b85d9224-310b-409b-891e-c903f5a40568` and the `url` attribute value
    /// defined for the resource, you would import it as:
    /// 
    /// When importing a Heroku drain resource, the ID must be built using the app name colon the unique ID from the Heroku API.
    /// For an app named `production-api` with a drain ID of `b85d9224-310b-409b-891e-c903f5a40568` and the `sensitive_url` attribute value
    /// defined for the resource, you would import it as:
    /// </summary>
    [HerokuResourceType("heroku:drain/drain:Drain")]
    public partial class Drain : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Heroku app ID (do not use app name)
        /// </summary>
        [Output("appId")]
        public Output<string> AppId { get; private set; } = null!;

        [Output("sensitiveUrl")]
        public Output<string?> SensitiveUrl { get; private set; } = null!;

        /// <summary>
        /// The unique token for your created drain.
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        /// <summary>
        /// The URL for Heroku to drain your logs to. Either `url` or `sensitive_url` must be defined.
        /// </summary>
        [Output("url")]
        public Output<string?> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Drain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Drain(string name, DrainArgs args, CustomResourceOptions? options = null)
            : base("heroku:drain/drain:Drain", name, args ?? new DrainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Drain(string name, Input<string> id, DrainState? state = null, CustomResourceOptions? options = null)
            : base("heroku:drain/drain:Drain", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumiverse",
                AdditionalSecretOutputs =
                {
                    "sensitiveUrl",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Drain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Drain Get(string name, Input<string> id, DrainState? state = null, CustomResourceOptions? options = null)
        {
            return new Drain(name, id, state, options);
        }
    }

    public sealed class DrainArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Heroku app ID (do not use app name)
        /// </summary>
        [Input("appId", required: true)]
        public Input<string> AppId { get; set; } = null!;

        [Input("sensitiveUrl")]
        private Input<string>? _sensitiveUrl;
        public Input<string>? SensitiveUrl
        {
            get => _sensitiveUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sensitiveUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The URL for Heroku to drain your logs to. Either `url` or `sensitive_url` must be defined.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public DrainArgs()
        {
        }
        public static new DrainArgs Empty => new DrainArgs();
    }

    public sealed class DrainState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Heroku app ID (do not use app name)
        /// </summary>
        [Input("appId")]
        public Input<string>? AppId { get; set; }

        [Input("sensitiveUrl")]
        private Input<string>? _sensitiveUrl;
        public Input<string>? SensitiveUrl
        {
            get => _sensitiveUrl;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _sensitiveUrl = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The unique token for your created drain.
        /// </summary>
        [Input("token")]
        public Input<string>? Token { get; set; }

        /// <summary>
        /// The URL for Heroku to drain your logs to. Either `url` or `sensitive_url` must be defined.
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public DrainState()
        {
        }
        public static new DrainState Empty => new DrainState();
    }
}
