// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Heroku.Space.Outputs
{

    [OutputType]
    public sealed class VpnConnectionTunnel
    {
        /// <summary>
        /// The public IP address of the tunnel.
        /// </summary>
        public readonly string? Ip;
        /// <summary>
        /// The pre-shared IPSec secret for the tunnel.
        /// </summary>
        public readonly string? PreSharedKey;

        [OutputConstructor]
        private VpnConnectionTunnel(
            string? ip,

            string? preSharedKey)
        {
            Ip = ip;
            PreSharedKey = preSharedKey;
        }
    }
}
