// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package addon

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-heroku/sdk/go/heroku/internal"
)

func LookupAddon(ctx *pulumi.Context, args *LookupAddonArgs, opts ...pulumi.InvokeOption) (*LookupAddonResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAddonResult
	err := ctx.Invoke("heroku:addon/getAddon:getAddon", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAddon.
type LookupAddonArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getAddon.
type LookupAddonResult struct {
	AppId      string   `pulumi:"appId"`
	ConfigVars []string `pulumi:"configVars"`
	Id         string   `pulumi:"id"`
	Name       string   `pulumi:"name"`
	Plan       string   `pulumi:"plan"`
	ProviderId string   `pulumi:"providerId"`
}

func LookupAddonOutput(ctx *pulumi.Context, args LookupAddonOutputArgs, opts ...pulumi.InvokeOption) LookupAddonResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupAddonResult, error) {
			args := v.(LookupAddonArgs)
			r, err := LookupAddon(ctx, &args, opts...)
			var s LookupAddonResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupAddonResultOutput)
}

// A collection of arguments for invoking getAddon.
type LookupAddonOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupAddonOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAddonArgs)(nil)).Elem()
}

// A collection of values returned by getAddon.
type LookupAddonResultOutput struct{ *pulumi.OutputState }

func (LookupAddonResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAddonResult)(nil)).Elem()
}

func (o LookupAddonResultOutput) ToLookupAddonResultOutput() LookupAddonResultOutput {
	return o
}

func (o LookupAddonResultOutput) ToLookupAddonResultOutputWithContext(ctx context.Context) LookupAddonResultOutput {
	return o
}

func (o LookupAddonResultOutput) AppId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAddonResult) string { return v.AppId }).(pulumi.StringOutput)
}

func (o LookupAddonResultOutput) ConfigVars() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAddonResult) []string { return v.ConfigVars }).(pulumi.StringArrayOutput)
}

func (o LookupAddonResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAddonResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAddonResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAddonResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupAddonResultOutput) Plan() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAddonResult) string { return v.Plan }).(pulumi.StringOutput)
}

func (o LookupAddonResultOutput) ProviderId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAddonResult) string { return v.ProviderId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAddonResultOutput{})
}
