// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Heroku.Pipeline.Inputs
{

    public sealed class PipelineOwnerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The unique identifier (UUID) of a pipeline owner.
        /// </summary>
        [Input("id", required: true)]
        public Input<string> Id { get; set; } = null!;

        /// <summary>
        /// The type of pipeline owner. Can be either `user` or `team`.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public PipelineOwnerArgs()
        {
        }
        public static new PipelineOwnerArgs Empty => new PipelineOwnerArgs();
    }
}
