// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Heroku.App.Outputs
{

    [OutputType]
    public sealed class GetAppOrganizationResult
    {
        public readonly bool Locked;
        public readonly string Name;
        public readonly bool Personal;

        [OutputConstructor]
        private GetAppOrganizationResult(
            bool locked,

            string name,

            bool personal)
        {
            Locked = locked;
            Name = name;
            Personal = personal;
        }
    }
}
