// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ProviderCustomization {
    setAddonConfigVarsInState?: pulumi.Input<boolean>;
    setAppAllConfigVarsInState?: pulumi.Input<boolean>;
}

export interface ProviderDelays {
    postAppCreateDelay?: pulumi.Input<number>;
    postDomainCreateDelay?: pulumi.Input<number>;
    postSpaceCreateDelay?: pulumi.Input<number>;
}

export interface ProviderTimeouts {
    addonCreateTimeout?: pulumi.Input<number>;
}
export namespace app {
    export interface AppOrganization {
        locked?: pulumi.Input<boolean>;
        name: pulumi.Input<string>;
        personal?: pulumi.Input<boolean>;
    }

}

export namespace build {
    export interface BuildSource {
        checksum?: pulumi.Input<string>;
        path?: pulumi.Input<string>;
        url?: pulumi.Input<string>;
        version?: pulumi.Input<string>;
    }

    export interface BuildUser {
        email?: pulumi.Input<string>;
        id?: pulumi.Input<string>;
    }
}

export namespace config {
}

export namespace pipeline {
    export interface PipelineOwner {
        id: pulumi.Input<string>;
        type: pulumi.Input<string>;
    }
}

export namespace review {
    export interface AppConfigDeployTarget {
        id: pulumi.Input<string>;
        type: pulumi.Input<string>;
    }
}

export namespace slug {
    export interface SlugBlob {
        method?: pulumi.Input<string>;
        url?: pulumi.Input<string>;
    }
}

export namespace space {
    export interface InboundRulesetRule {
        action: pulumi.Input<string>;
        source: pulumi.Input<string>;
    }

    export interface VpnConnectionTunnel {
        ip?: pulumi.Input<string>;
        preSharedKey?: pulumi.Input<string>;
    }
}

export namespace team {
}
