// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package app

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupApp(ctx *pulumi.Context, args *LookupAppArgs, opts ...pulumi.InvokeOption) (*LookupAppResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupAppResult
	err := ctx.Invoke("heroku:app/getApp:getApp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getApp.
type LookupAppArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getApp.
type LookupAppResult struct {
	Acm            bool                   `pulumi:"acm"`
	Buildpacks     []string               `pulumi:"buildpacks"`
	ConfigVars     map[string]interface{} `pulumi:"configVars"`
	GitUrl         string                 `pulumi:"gitUrl"`
	HerokuHostname string                 `pulumi:"herokuHostname"`
	// The provider-assigned unique ID for this managed resource.
	Id              string               `pulumi:"id"`
	InternalRouting bool                 `pulumi:"internalRouting"`
	Name            string               `pulumi:"name"`
	Organizations   []GetAppOrganization `pulumi:"organizations"`
	Region          string               `pulumi:"region"`
	Space           string               `pulumi:"space"`
	Stack           string               `pulumi:"stack"`
	Uuid            string               `pulumi:"uuid"`
	WebUrl          string               `pulumi:"webUrl"`
}

func LookupAppOutput(ctx *pulumi.Context, args LookupAppOutputArgs, opts ...pulumi.InvokeOption) LookupAppResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupAppResult, error) {
			args := v.(LookupAppArgs)
			r, err := LookupApp(ctx, &args, opts...)
			var s LookupAppResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupAppResultOutput)
}

// A collection of arguments for invoking getApp.
type LookupAppOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupAppOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppArgs)(nil)).Elem()
}

// A collection of values returned by getApp.
type LookupAppResultOutput struct{ *pulumi.OutputState }

func (LookupAppResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAppResult)(nil)).Elem()
}

func (o LookupAppResultOutput) ToLookupAppResultOutput() LookupAppResultOutput {
	return o
}

func (o LookupAppResultOutput) ToLookupAppResultOutputWithContext(ctx context.Context) LookupAppResultOutput {
	return o
}

func (o LookupAppResultOutput) Acm() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAppResult) bool { return v.Acm }).(pulumi.BoolOutput)
}

func (o LookupAppResultOutput) Buildpacks() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupAppResult) []string { return v.Buildpacks }).(pulumi.StringArrayOutput)
}

func (o LookupAppResultOutput) ConfigVars() pulumi.MapOutput {
	return o.ApplyT(func(v LookupAppResult) map[string]interface{} { return v.ConfigVars }).(pulumi.MapOutput)
}

func (o LookupAppResultOutput) GitUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.GitUrl }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) HerokuHostname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.HerokuHostname }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAppResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) InternalRouting() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupAppResult) bool { return v.InternalRouting }).(pulumi.BoolOutput)
}

func (o LookupAppResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) Organizations() GetAppOrganizationArrayOutput {
	return o.ApplyT(func(v LookupAppResult) []GetAppOrganization { return v.Organizations }).(GetAppOrganizationArrayOutput)
}

func (o LookupAppResultOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Region }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) Space() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Space }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) Stack() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Stack }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func (o LookupAppResultOutput) WebUrl() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAppResult) string { return v.WebUrl }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAppResultOutput{})
}
