// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Heroku.Inputs
{

    public sealed class ProviderCustomizationArgs : global::Pulumi.ResourceArgs
    {
        [Input("setAddonConfigVarsInState")]
        public Input<bool>? SetAddonConfigVarsInState { get; set; }

        [Input("setAppAllConfigVarsInState")]
        public Input<bool>? SetAppAllConfigVarsInState { get; set; }

        public ProviderCustomizationArgs()
        {
        }
        public static new ProviderCustomizationArgs Empty => new ProviderCustomizationArgs();
    }
}
