name: main

on:
  push:
    branches:
      - main
      - 'feature/**'
      - 'dependabot/**'
    tags-ignore:
      - v*
  workflow_dispatch:

jobs:
  prerequisites:
    uses: pulumiverse/infra/.github/workflows/provider-prerequisites.yaml@actions-workflows-v0.0.4
    with:
      provider: heroku
      goversion: 1.20.x
  build:
    needs: prerequisites
    uses: pulumiverse/infra/.github/workflows/provider-build-sdk.yaml@actions-workflows-v0.0.4
    with:
      provider: heroku
      goversion: 1.20.x
      dotnetversion: 6.0.120
      nodeversion: 16.x
      pythonversion: 3.11
